greeting: toplevel-local
imageDataDir: /tmp
toplevel: props
server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
spring:
  application:
    name: api
  cloud:
    discovery:
      enabled: false
    config:
      discovery:
        enabled: false
      enabled: false
  zipkin:
    enabled: false
  # profiles:
  #   active: test
  # config:
  #   import: optional:configserver:${CONFIG_SERVER}
