management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
spring:
  application:
    name: api
  profiles:
    active: local
  config:
    import: optional:configserver:${CONFIG_SERVER}
